# Generated by Django 2.2.8 on 2019-12-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Peut lire tous les livres')]},
        ),
    ]
